// <auto-generated />
using System;
using EducAIte.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducAIteSolution.src.EducAIte.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326072651_AiANALYTICSENTITIES")]
    partial class AiANALYTICSENTITIES
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducAIte.Domain.Entities.Certification", b =>
                {
                    b.Property<long>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CertificationId"));

                    b.Property<string>("CertificationKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("CertificationId");

                    b.HasIndex("CertificationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Certifications_CertificationKey");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Certifications_StudentId");

                    b.ToTable("Certifications", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("EDPCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("StudyLoadId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Units")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("CourseId");

                    b.HasIndex("EDPCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Courses_EDPCode");

                    b.HasIndex("StudyLoadId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileMetadataId")
                        .HasColumnType("bigint");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentId");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("FolderId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<long>("FileMetaDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FileMetaDataId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("FileMetaDataId");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_FileMetadata_StorageKey");

                    b.HasIndex("StudentId");

                    b.ToTable("FileMetadata", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Flashcard", b =>
                {
                    b.Property<long>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FlashcardId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("NoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FlashcardId");

                    b.HasIndex("NoteId");

                    b.ToTable("Flashcards", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardAnswerHistory", b =>
                {
                    b.Property<long>("FlashcardAnswerHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FlashcardAnswerHistoryId"));

                    b.Property<int?>("AiQualityScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("ExpectedAnswerSnapshot")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("FallbackQualityScore")
                        .HasColumnType("integer");

                    b.Property<int>("FinalQualityScore")
                        .HasColumnType("integer");

                    b.Property<long?>("FlashcardSessionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FlashcardSessionItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("ScoringSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<long>("StudentFlashcardId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubmittedAnswer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("WasAcceptedAsCorrect")
                        .HasColumnType("boolean");

                    b.HasKey("FlashcardAnswerHistoryId");

                    b.HasIndex("FlashcardSessionId");

                    b.HasIndex("FlashcardSessionItemId");

                    b.HasIndex("StudentFlashcardId", "AnsweredAt");

                    b.ToTable("FlashcardAnswerHistories", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardSession", b =>
                {
                    b.Property<long>("FlashcardSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FlashcardSessionId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("CurrentItemIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RestartedFromSessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("ScopeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long?>("StudentCourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("FlashcardSessionId");

                    b.HasIndex("StudentCourseId");

                    b.HasIndex("StudentId", "StudentCourseId", "ScopeType", "Status");

                    b.ToTable("FlashcardSessions", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardSessionItem", b =>
                {
                    b.Property<long>("FlashcardSessionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FlashcardSessionItemId"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("CurrentOrder")
                        .HasColumnType("integer");

                    b.Property<long>("FlashcardSessionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("LastAnswerHistoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginalOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PresentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("StudentFlashcardId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("FlashcardSessionItemId");

                    b.HasIndex("StudentFlashcardId");

                    b.HasIndex("FlashcardSessionId", "CurrentOrder");

                    b.ToTable("FlashcardSessionItems", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Folder", b =>
                {
                    b.Property<long>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FolderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FolderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ParentFolderId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Semester")
                        .HasColumnType("smallint");

                    b.Property<long>("StudentCourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("FolderId");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("StudentCourseId");

                    b.HasIndex("StudentId", "FolderKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Folders_Student_FolderKey");

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Grade", b =>
                {
                    b.Property<long>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GradeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("GradeType")
                        .HasColumnType("integer");

                    b.Property<decimal>("GradeValue")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("StudentCourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentCourseId", "GradeType")
                        .HasDatabaseName("IX_Grades_StudentCourse_GradeType");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Note", b =>
                {
                    b.Property<long>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(30,15)")
                        .HasDefaultValue(100m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoteId");

                    b.HasIndex("DocumentId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Notes_DocumentId_SequenceNumber");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Resume", b =>
                {
                    b.Property<long>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ResumeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("ResumeKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("ResumeId");

                    b.HasIndex("ResumeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Resumes_ResumeKey");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Resumes_StudentId");

                    b.ToTable("Resumes", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Program")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Students_Email");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Students_StudentIdNumber");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCourse", b =>
                {
                    b.Property<long>("StudentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentCourseId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("StudyLoadId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("StudentCourseId");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_StudentCourses_CourseId");

                    b.HasIndex("StudyLoadId")
                        .HasDatabaseName("IX_StudentCourses_StudyLoadId");

                    b.HasIndex("CourseId", "StudyLoadId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentCourses_Course_StudyLoad");

                    b.ToTable("StudentCourses", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCoursePerformanceSummary", b =>
                {
                    b.Property<long>("StudentCourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("AiInsight")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("AiLastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AiStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<decimal>("FlashcardAccuracyRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("ImprovementSuggestion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LearningRetentionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("MasteredFlashcardsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverallPerformanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("RiskLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("TrackedFlashcardsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("StudentCourseId");

                    b.ToTable("StudentCoursePerformanceSummaries", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentFlashcard", b =>
                {
                    b.Property<long>("StudentFlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentFlashcardId"));

                    b.Property<int>("ConsecutiveCorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ConsecutiveWrongCount")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<long>("FlashcardId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LapseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("LastReviewOutcome")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextReviewAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("StudentCourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("WrongCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("StudentFlashcardId");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("StudentId", "FlashcardId")
                        .IsUnique();

                    b.HasIndex("StudentId", "NextReviewAt");

                    b.ToTable("StudentFlashcards", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentFlashcardAnalytics", b =>
                {
                    b.Property<long>("StudentFlashcardId")
                        .HasColumnType("bigint");

                    b.Property<string>("AiInsight")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("AiLastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AiStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<decimal>("ConfidenceScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ConsistencyScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<decimal>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(2.50m);

                    b.Property<string>("ImprovementSuggestion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<int>("LapseCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MasteryLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("RetentionScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("RiskLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("StudentFlashcardId");

                    b.ToTable("StudentFlashcardAnalytics", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentOverallPerformanceSummary", b =>
                {
                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("AiInsight")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("AiLastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AiStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<decimal>("FlashcardAccuracyRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("ImprovementSuggestion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LearningRetentionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("MasteredFlashcardsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverallPerformanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("RiskLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("TrackedCoursesCount")
                        .HasColumnType("integer");

                    b.Property<int>("TrackedFlashcardsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("StudentId");

                    b.ToTable("StudentOverallPerformanceSummaries", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudyLoad", b =>
                {
                    b.Property<long>("StudyLoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudyLoadId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<long>("FileMetadataId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SchoolYearEnd")
                        .HasColumnType("integer")
                        .HasColumnName("SchoolYearEnd");

                    b.Property<int>("SchoolYearStart")
                        .HasColumnType("integer")
                        .HasColumnName("SchoolYearStart");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.HasKey("StudyLoadId");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "SchoolYearStart", "SchoolYearEnd", "Semester")
                        .IsUnique()
                        .HasDatabaseName("IX_StudyLoads_StudentSchoolYearSemesterUnique");

                    b.ToTable("StudyLoads", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Certification", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("Certifications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Course", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.StudyLoad", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudyLoadId");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Document", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Folder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileMetadata");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FileMetadata", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Note", "Note")
                        .WithMany("Flashcards")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardAnswerHistory", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.FlashcardSession", "FlashcardSession")
                        .WithMany()
                        .HasForeignKey("FlashcardSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducAIte.Domain.Entities.FlashcardSessionItem", "FlashcardSessionItem")
                        .WithMany()
                        .HasForeignKey("FlashcardSessionItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducAIte.Domain.Entities.StudentFlashcard", "StudentFlashcard")
                        .WithMany()
                        .HasForeignKey("StudentFlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardSession");

                    b.Navigation("FlashcardSessionItem");

                    b.Navigation("StudentFlashcard");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardSession", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.StudentCourse", "StudentCourse")
                        .WithMany("FlashcardSessions")
                        .HasForeignKey("StudentCourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("FlashcardSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardSessionItem", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.FlashcardSession", "FlashcardSession")
                        .WithMany("Items")
                        .HasForeignKey("FlashcardSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.StudentFlashcard", "StudentFlashcard")
                        .WithMany()
                        .HasForeignKey("StudentFlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardSession");

                    b.Navigation("StudentFlashcard");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Folder", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EducAIte.Domain.Entities.StudentCourse", "StudentCourse")
                        .WithMany("Folders")
                        .HasForeignKey("StudentCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("Folders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EducAIte.Domain.ValueObjects.SchoolYear", "SchoolYear", b1 =>
                        {
                            b1.Property<long>("FolderId")
                                .HasColumnType("bigint");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearEnd");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearStart");

                            b1.HasKey("FolderId");

                            b1.ToTable("Folders");

                            b1.WithOwner()
                                .HasForeignKey("FolderId");
                        });

                    b.Navigation("ParentFolder");

                    b.Navigation("SchoolYear")
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Grade", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.StudentCourse", "StudentCourse")
                        .WithMany("Grades")
                        .HasForeignKey("StudentCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Note", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Document", "Document")
                        .WithMany("Notes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Resume", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCourse", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.StudyLoad", "StudyLoad")
                        .WithMany()
                        .HasForeignKey("StudyLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("StudyLoad");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCoursePerformanceSummary", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.StudentCourse", "StudentCourse")
                        .WithOne()
                        .HasForeignKey("EducAIte.Domain.Entities.StudentCoursePerformanceSummary", "StudentCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentFlashcard", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Flashcard", "Flashcard")
                        .WithMany("StudentFlashcards")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("StudentFlashcards")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentFlashcardAnalytics", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.StudentFlashcard", "StudentFlashcard")
                        .WithOne()
                        .HasForeignKey("EducAIte.Domain.Entities.StudentFlashcardAnalytics", "StudentFlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentFlashcard");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentOverallPerformanceSummary", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithOne()
                        .HasForeignKey("EducAIte.Domain.Entities.StudentOverallPerformanceSummary", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudyLoad", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("StudyLoads")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileMetadata");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Document", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Flashcard", b =>
                {
                    b.Navigation("StudentFlashcards");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FlashcardSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Note", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Student", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("FlashcardSessions");

                    b.Navigation("Folders");

                    b.Navigation("StudentFlashcards");

                    b.Navigation("StudyLoads");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCourse", b =>
                {
                    b.Navigation("FlashcardSessions");

                    b.Navigation("Folders");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudyLoad", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
