// <auto-generated />
using System;
using EducAIte.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducAIteSolution.src.EducAIte.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducAIte.Domain.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("EDPCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<byte>("Units")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CourseId");

                    b.HasIndex("EDPCode")
                        .IsUnique()
                        .HasDatabaseName("IDX_Courses_EDPCode");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<long>("FileMetadataId")
                        .HasColumnType("bigint");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IDX_Documents_ExternalId");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("FolderId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<long>("FileMetaDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FileMetaDataId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FileMetaDataId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("FileMetadata", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Flashcard", b =>
                {
                    b.Property<long>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FlashcardId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<long>("NoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FlashcardId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("NoteId");

                    b.ToTable("Flashcards", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Folder", b =>
                {
                    b.Property<long>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FolderId"));

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FolderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ParentFolderId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Semester")
                        .HasColumnType("smallint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FolderId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("StudentId", "FolderKey")
                        .IsUnique();

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Grade", b =>
                {
                    b.Property<long>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GradeId"));

                    b.Property<int>("GradeType")
                        .HasColumnType("integer");

                    b.Property<decimal>("GradeValue")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<long>("StudentCourseId")
                        .HasColumnType("bigint");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentCourseId", "GradeType");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Note", b =>
                {
                    b.Property<long>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoteId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Program")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentIdNumber")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCourse", b =>
                {
                    b.Property<long>("StudentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentCourseId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudyLoadId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("StudentCourses", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentFlashcard", b =>
                {
                    b.Property<long>("StudentFlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudentFlashcardId"));

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("FlashcardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MasteryLevel")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.0m);

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("WrongCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("StudentFlashcardId");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("FolderId");

                    b.HasIndex("StudentId", "FlashcardId")
                        .IsUnique();

                    b.ToTable("StudentFlashcards", (string)null);
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudyLoad", b =>
                {
                    b.Property<long>("StudyLoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StudyLoadId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileMetadataId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudyLoadId");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudyLoads", (string)null);
                });

            modelBuilder.Entity("StudyLoadCourses", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudyLoadId")
                        .HasColumnType("bigint");

                    b.HasKey("CourseId", "StudyLoadId");

                    b.HasIndex("StudyLoadId", "CourseId")
                        .IsUnique();

                    b.ToTable("StudyLoadCourses");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Document", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Folder", "Folder")
                        .WithMany("Documents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileMetadata");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.FileMetadata", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducAIte.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Document");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Folder", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducAIte.Domain.Entities.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("Folders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EducAIte.Domain.ValueObjects.SchoolYear", "SchoolYear", b1 =>
                        {
                            b1.Property<long>("FolderId")
                                .HasColumnType("bigint");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearEnd");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearStart");

                            b1.HasKey("FolderId");

                            b1.ToTable("Folders");

                            b1.WithOwner()
                                .HasForeignKey("FolderId");
                        });

                    b.Navigation("Course");

                    b.Navigation("ParentFolder");

                    b.Navigation("SchoolYear")
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Grade", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.StudentCourse", "StudentCourse")
                        .WithMany("Grades")
                        .HasForeignKey("StudentCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Note", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCourse", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EducAIte.Domain.ValueObjects.SchoolYear", "SchoolYear", b1 =>
                        {
                            b1.Property<long>("StudentCourseId")
                                .HasColumnType("bigint");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearEnd");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearStart");

                            b1.HasKey("StudentCourseId");

                            b1.ToTable("StudentCourses");

                            b1.WithOwner()
                                .HasForeignKey("StudentCourseId");
                        });

                    b.Navigation("Course");

                    b.Navigation("SchoolYear")
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentFlashcard", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Flashcard", "Flashcard")
                        .WithMany()
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Folder", null)
                        .WithMany("StudentFlashcards")
                        .HasForeignKey("FolderId");

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("Flashcards")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudyLoad", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.Student", "Student")
                        .WithMany("StudyLoads")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EducAIte.Domain.ValueObjects.SchoolYear", "SchoolYear", b1 =>
                        {
                            b1.Property<long>("StudyLoadId")
                                .HasColumnType("bigint");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearEnd");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("SchoolYearStart");

                            b1.HasKey("StudyLoadId");

                            b1.ToTable("StudyLoads");

                            b1.WithOwner()
                                .HasForeignKey("StudyLoadId");
                        });

                    b.Navigation("FileMetadata");

                    b.Navigation("SchoolYear")
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyLoadCourses", b =>
                {
                    b.HasOne("EducAIte.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducAIte.Domain.Entities.StudyLoad", null)
                        .WithMany()
                        .HasForeignKey("StudyLoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("StudentFlashcards");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.Student", b =>
                {
                    b.Navigation("EnrolledCourses");

                    b.Navigation("Flashcards");

                    b.Navigation("Folders");

                    b.Navigation("StudyLoads");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("EducAIte.Domain.Entities.StudentCourse", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
